### ISSUE TITLE
RFC: Modularization

### ISSUE THREAD

**Issue by mthjones** [slack-rs/slack-rs#14]
**Note**: This would be a large breaking change – probably a `0.10.0` or later release.

My thinking is that there's really two concepts in this crate: the RTM API support and the web API support. They would do well to be split into two modules: `slack::web` and `slack::rtm`.

`slack::web` would contain a module that would contain the low-level interface to the API. Essentially just wrapping a `hyper` call and returning a `hyper::Result`. This could be strictly internal or exposed publicly. It would also contain a higher-level interface that uses the low-level interface but actually parses the results, returns Slack errors (i.e. `SlackError::InvalidAuth` or `SlackError::ChannelNotFound`) where appropriate, and typed objects like the existing `User` and `Channel` for example.

`slack::rtm` would be structured very similarly, but only dealing with the RTM side of things.

Thoughts?

**Comment by BenTheElder** [comment]
I think this is a good idea internally, but I'd like to keep the external
api convenient.
Sstoring the token once in one client that can interact with the various
apis seems very sane/convenient, perhaps we could embed a slack::web client
in the rtm client so that at the top level you can still use one client
object?

**Comment by mthjones** [comment]
Hmm, I think that makes sense for sure. That is how the [official Slack client](https://github.com/slackhq/node-slack-client) library is setup, so I'd say it makes sense to follow their lead here. I think retaining the two as separate public modules that can be used explicitly while also having a top-level client that joins the two would be the best of both worlds.

Another orthogonal concept that might be fun to explore would be defining traits in the package for the different Slack concepts (e.g. `Messageable` is implemented for `User` and `Group`, etc.).

**Comment by BenTheElder** [comment]
That all sounds good. I'm focusing on errors and timestamps etc right now but I'd welcome changes that make the library more flexible (the 3 clients), as far as the traits idea, I think it'd be fun/useful to have some kind of easy message building. I'll have to look more at the official client tomorrow.

Perhaps we could have a `slack::Message` object (for sending messages) that can be built.
Being able to do something like (not sure about method names etc, but roughly): 
`let message = Message::from("Hello").mention_user(client.get_user("mthjones")).str(".");`
and then:
 `client.send_message(&message);`
would make complex messages a lot easier to send, and abstract away from the formatting requirements.

It would also probably mean the api wouldn't need to let users set all of the optional parse options as we'd handle that ourselves when serializing the message and sending it.

**Comment by mthjones** [comment]
I really like that idea about building messages. It might be useful for messages, but for Attachments it would be huge. My current project has something like:

```rust
let attachment = slack::api::Attachment {
    fallback: format!("*New Pull Request!\n*{}*\nAssigned to: {}", pr.title, reviewers.join(", ")),
    color: Some("#00CC99".to_owned()),
    pretext: None,
    author_name: Some(pr.author.user.name.clone()),
    author_link: Some(pr.author.user.links.get("self").unwrap()[0].href.clone()),
    author_icon: None,
    title: Some(pr.title.clone()),
    title_link: Some(pr.links.get("self").unwrap()[0].href.clone()),
    text: pr.description.clone().unwrap_or("".to_owned()),
    fields: Some(vec![reviewers_field]),
    image_url: None,
    thumb_url: None
};
```

which is really messy. I'd love to have something more like a builder:

```rust
let mut attachment_builder = AttachmentBuilder::with_text_and_fallback(
    pr.description.clone().unwrap_or("".to_owned()),
    format!("*New Pull Request!\n*{}*\nAssigned to: {}", pr.title, reviewers.join(", "))
);
let attachment = attachment_builder
    .with_color("#00CC99")
    .with_author(Some(pr.author.user.name.clone()), Some(pr.author.user.links.get("self").unwrap()[0].href.clone()), None)
    .add_field(reviewers_field)
    .build();
```

**Comment by BenTheElder** [comment]
I agree, something along those lines is definitely on the TODO list. Being able to build messages etc using the (de/)serialized types would be much cleaner than leaving it up to the end user to manually format json or only supporting plain text.

I haven't yet done the builder pattern in rust, but that looks like the most clean/idiomatic route (like above).

**Comment by mthjones** [comment]
In working with this crate some more, I'm finding I generally only need *either* the `RtmClient` or the web APIs. I'm considering moving the web APIs out into another crate that could be managed independently of this one. This crate could then have a dependency on that one for what it needs to use.

Some thoughts:
* I saw there were some issues around compile times with this library. Especially during development of this crate, this should help keep compile times down due to not having to recompile the entire API module every time... or we could wait until incremental compilation is implemented... :)
* Seems unnecessary to have to pull in a dependency on `websocket` just to call HTTP APIs
* Allows independent updating of the crates

If we go this route, I could copy the API into a new project in a new repo and publish it, or this repo could be restructured to support both crates.

**Comment by BenTheElder** [comment]
How would you handle the API types? A third crate?

**Comment by BenTheElder** [comment]
Or would those just be re-exposed from the web crate in the rtm crate?

**Comment by mthjones** [comment]
I think re-exporting them would make the most sense.

**Comment by BenTheElder** [comment]
I think that sounds like a good plan, bringing down compile times would be
nice and the web API could make a nice smaller crate.
I don't suppose cargo allows sub crates in the same repository now does it?

**Comment by mthjones** [comment]
I don't think cargo cares about the repository at all, just the folder structure. In [one of my repos](https://github.com/mthjones/pierre) I have multiple crates in one repo, but they're also both binary projects so I'm also not deploying docs/releasing versions/etc. I'm not sure what effect it would have on those.

**Comment by BenTheElder** [comment]
As far as I remember, the last time I attempted this cargo allowed path
dependencies but not publishing projects with them.
I'm not sure if this is still true.

**Comment by mthjones** [comment]
Ah, but if they have a path dependency they'd need to both be packaged together anyways. I think using path dependencies only works when you're modularizing your library components for a binary, like servo.

**Comment by BenTheElder** [comment]
Yeah. It looks like your project just pushes cargo.toml down a directory.
We could maybe have something like slack-rs/web and slack-rs/rtm

**Comment by mthjones** [comment]
Yeah, that could work. Though I feel like putting multiple lib crates in one repo is going to complicate things like Travis testing, docs building, issue reporting, etc. Would you prefer to keep the two crates in the one repo? We could try to figure it out.

**Comment by BenTheElder** [comment]
I think it might be better to split it up into two repositories, i'm
looking at creating an organization to move them to.

**Comment by mthjones** [comment]
Now that the organization and the two repos are set up, I'm going to close this issue. Some of the other discussions in here would be better served to have their own issues filed.
