### ISSUE TITLE
on_close not called when entering flightmode

### ISSUE THREAD

**Issue by dten** [slack-rs/slack-rs#31]
on_close is never fired. After connecting, i switch laptop to flightmode, wait up to a minute or two and nothing happens. Switch flightmode off and nothing happens also, but the bot never gets any more messages.
I see this on Ubuntu and Windows 10 by the way

**Comment by BenTheElder** [comment]
cc https://github.com/cyderize/rust-websocket/issues/66

**Comment by BenTheElder** [comment]
I think we may be able to mitigate this by setting a read timeout on the underlying socket but I'm not positive. I've been able to reproduce so far on OSX but I don't have a solution yet.

Unfortunately I don't have much time to work on this currently, but I'll get to it eventually and I'll accept any help or pull requests in the meantime.

**Comment by BenTheElder** [comment]
I beleive this should have been closed by https://github.com/slack-rs/slack-rs/pull/33
