### ISSUE TITLE
Update Travis for restructure.

### ISSUE THREAD

**Issue by BenTheElder** [slack-rs/slack-rs#45]
We need to update the Travis config for the restructuring and it would also be nice to automate publishing to crates.io

This is an umbrella issue for discussing the necessary changes.

**Comment by BenTheElder** [comment]
Whoops. I suppose assigning you is accurate enough, but that was unintended. (Posted from my phone).

**Comment by BenTheElder** [comment]
The biggest problem I see, is that I do not know how to move permission for publishing the `slack-rs` package to the organization account and set up the relevant token/keys in travis.

Currently i publish from my laptop after authorizing my github account with cargo/crates.io. We'll need to solve this, otherwise the changes should be fairly straightforward I think.

**Comment by mthjones** [comment]
In my experience, using Travis with an organization has been a breeze. Just need to regenerate the token in `.travis.yml`. Don't know if I have the correct permissions for the org to do that, but I'll take a look.

**Comment by BenTheElder** [comment]
You should have admin privileges within the group, if that doesn't cover it I can generate it.

For publishing though, I haven't found anything yet for publishing to crates.io from an organization let alone transitioning from a user to an organization. I'll look again later if you don't sort that out first.

**Comment by mthjones** [comment]
Looks like there are other crates doing it the way I was thinking: https://github.com/Nemo157/roaring-rs/blob/master/.travis.yml

I'll dig into it later tonight.

**Comment by BenTheElder** [comment]
Excellent, that does look convenient.

**Comment by mthjones** [comment]
I believe I have a working implementation on `slack-rs-api`. Going to attempt a version bump and see what happens.

**Comment by mthjones** [comment]
[Great success](http://slack-rs.github.io/slack-rs-api/slack_api/index.html)! I'll look at updating this .travis.yml to work the same way.

**Comment by mthjones** [comment]
Hmm, I need to encrypt a crates.io token in the `.travis.yml`. Right now it has to be yours, because you're the only owner on the `slack` crate. I could push the changes as they are now and you could add the token yourself (`travis encrypt CRATES_IO_TOKEN=<your token here> --add`), or you could add me as an owner on this crate (`cargo add --owner mthjones`) and I can encrypt my own token.

**Comment by BenTheElder** [comment]
I can definitely encrypt my token but when i check `cargo help` `cargo add` is not a subcommand on my machine running stable from rust 1.7.0.

**Comment by mthjones** [comment]
Ack, sorry. I did that backwards. Should be `cargo owner --add mthjones`.

**Comment by mthjones** [comment]
I'll push the change to a branch and put the PR up.

**Comment by BenTheElder** [comment]
I'm adding the `github:slack-rs:maintainers` group as an owner, which
appears to be an option that will further automate this sort of thing in
the future: (ref: http://doc.crates.io/crates-io.html#cargo-owner)
