### ISSUE TITLE
Confusing docs for ReconnectUrl

### ISSUE THREAD

**Issue by fenhl** [slack-rs/slack-rs#49]
The docs for [`slack::Event::ReconnectUrl`](http://slack-rs.github.io/slack-rs/slack/enum.Event.html#variant.ReconnectUrl) say:

> Represents the slack [`reconnect_url`](https://api.slack.com/event/reconnect_url) event.

The link is a 404 and the Slack docs mention no such event, and yet I am receiving these. What's going on?

**Comment by BenTheElder** [comment]
Slack has a relatively undocumented event for this here:
https://api.slack.com/events/reconnect_url
I'm not sure what the URL in the docs is currently but I'll fix it when I
get a moment.

**Comment by BenTheElder** [comment]
Looks like it changed from event to events in the URL on slack's part.

**Comment by BenTheElder** [comment]
If anyone knows more about this, please open a PR to fix. The slack docs for this appear to have been removed entirely (?)

**Comment by BenTheElder** [comment]
The current [docs](https://api.slack.com/events/reconnect_url) say:
> The reconnect_url event is currently unsupported and experimental.

We should update the url in our docs, but otherwise this probably actually shouldn't be better documented since it is unsupported upstream, other than perhaps to note that.

**Comment by joehanna** [comment]
Can we turn the event off?  I am getting this event precisely every three minutes using RTM API.  Seems like unnecessary chatter considering it is experimental and has no practical or advertised use right now.

**Comment by dten** [comment]
Why not just ignore them?
```
        if let Some(&slack::Event::ReconnectUrl) = event.as_ref().ok() {
            return;
        }
```

**Comment by joehanna** [comment]
Yeah - I'm doing that. Just thought it would be good if we could turn off certain RTM events for some channels. Unnecessary traffic and work for the app for no benefit.

**Comment by dten** [comment]
You can't ask slack to not send it so the data will still come and it will be parsed

**Comment by joehanna** [comment]
I guess so

**Comment by BenTheElder** [comment]
I'm going to finally close this for now. The current slack docs for this are [here](https://api.slack.com/events/reconnect_url) and they state:
>The reconnect_url event is currently unsupported and experimental.
