### ISSUE TITLE
Allow async message sending

### ISSUE THREAD

**Issue by fenhl** [slack-rs/slack-rs#50]
Right now the way the API is constructed, we can only send messages from the `slack::EventHandler` implementation; that is, when an event or ping is received. This is very limiting, since it means we cannot send messages based on events generated by something other than Slack, like another thread. Would it be possible to redesign the interface to remove this limitation?

**Comment by BenTheElder** [comment]
You can also send messages using [post_message](http://slack-rs.github.io/slack-rs/slack/api/chat/fn.post_message.html) in the API crate.

**Comment by BenTheElder** [comment]
We could provide access to the message sending api (on the websocket) from multiple threads, you'd need to wrap the message id counter in an `Arc` (it's already atomic), and create a structure (`Sender`?) that contained a reference to the counter and a clone of the send half of the internal sync channel used to pass messages between your worker thread and the sending network thread.

I don't have time for this currently (_very_ heavy workload this semester), but I think we'd welcome a patch.

If you aren't to strongly tied to the RTM client's message sending api, the easiest route would be just using `post_message` to post to the http api endpoint from your other threads.
