### ISSUE TITLE
Possible Slack API/slack-rs JSON fields mismatch

### ISSUE THREAD

**Issue by kiyoto** [slack-rs/slack-rs#52]
I have [a program](https://github.com/kiyoto/acme_utils/blob/master/slacktail/src/main.rs) that uses this library (thanks for all the work!).

It crashes on several of the RTM messages. This is all I get upon a crash:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: JsonDecode(MissingFieldError("text"))', ../src/libcore/result.rs:741
```

I believe that slack-rs-api's message types aren't matching the JSON events coming from Slack, but is there anyway to run this library on a "debug mode" so that I can give you a better trace?

**Comment by BenTheElder** [comment]
Setting `RUST_BACKTRACE=1` when running a debug build should should provide more information.
EG: `RUST_BACKTRACE=1 cargo run foo`.

**Comment by kiyoto** [comment]
Thanks! Will let you know if I find out something more.

**Comment by kiyoto** [comment]
Ok, here's the stacktrace with RUST_BACKTRACE=1 cargo run <slack_api_token>` for the above program.

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: JsonDecode(MissingFieldError("text"))', ../src/libcore/result.rs:741
stack backtrace:
   1:        0x10db66148 - sys::backtrace::tracing::imp::write::h71b7c99a21cff148fMt
   2:        0x10db6799f - panicking::log_panic::_<closure>::closure.40876
   3:        0x10db67442 - panicking::log_panic::h2d79dd1ccae87ed8BFx
   4:        0x10db5b876 - sys_common::unwind::begin_unwind_inner::hb8ac08b8a72b9d1bhPs
   5:        0x10db5bc5e - sys_common::unwind::begin_unwind_fmt::h076ba7ed08690e9dnOs
   6:        0x10db65767 - rust_begin_unwind
   7:        0x10db88e00 - panicking::panic_fmt::h3967afc085fe8067LFK
   8:        0x10d78b1bd - result::_<impl>::unwrap::unwrap::h10098942936329436216
   9:        0x10d78aa93 - _<impl>::on_event::hb5900630e63d8c003da
  10:        0x10d79d888 - _<impl>::run::run::h5838927743405050467
  11:        0x10d79524d - _<impl>::login_and_run::login_and_run::h995944026564267767
  12:        0x10d7935eb - main::hf059bfaba1ef81910ha
  13:        0x10db671c2 - sys_common::unwind::try::try_fn::h4103587514840227558
  14:        0x10db65588 - __rust_try
  15:        0x10db67069 - rt::lang_start::h216753457f385fdaJCx
  16:        0x10d90d0f9 - main
Process didn't exit successfully: `/Users/kiyoto/rust-programs/slacktail/target/debug/slacktail xoxp-3522861600-3523048018-14491818720-aeadca1f68` (exit code: 101)
```

It looks like slack-rs-api is not handling certain events correctly. What other infor can I provide?

**Comment by kiyoto** [comment]
Ok, I'm closing this since the crash was caused by me not handling unwrap properly (sorry, week 2 of using Rust).

Independently, if I see actual type mismatches, I will open a new issue and report it there.

**Comment by BenTheElder** [comment]
It would be helpful if your `on_event` implementation wrote out the `raw_string` parameter before panic-ing when it receives an error result for `event`.

Instead of `unwrap()`-ing the event, match for `Ok` or `Err`, so that you can handle the error instead of just panic-ing (and log the raw event data before panicing or etc).

**Comment by BenTheElder** [comment]
I see you just determined that, thanks! I'll try to look into the parsing myself at some point. I may not have much time for a while.
