### ISSUE TITLE
Update ReactionAdded API's implementation

### ISSUE THREAD

**Issue by kiyoto** [slack-rs/slack-rs#53]
It looks like Slack has updated their API from [this](https://web.archive.org/web/20150920113244/https://api.slack.com/events/reaction_added) to [this](https://web.archive.org/web/20160316165112/https://api.slack.com/events/reaction_added). In particular,

* `name` field is replaced with `reaction` field.
* `item_user` field has been added.

**Comment by BenTheElder** [comment]
Closed by #54
