### ISSUE TITLE
Not reporting presence properly

### ISSUE THREAD

**Issue by ollivera** [slack-rs/slack-rs#58]
Hi,

I noticed that after some minutes the bot vanishes from the user list, but it is still running as it replies my messages.
 It seems that it doesn't report presence properly after some time. Is there anyway to keep it online or away?

Regards

**Comment by BenTheElder** [comment]
According to the docs this shouldn't be happening:

> presence - Bot users do not follow the usual rules for automatically being marked as away when inactive. In most cases you want a bot user to display as "active" and ready to respond, even if it hasn't posted a message in a while. Use the users.setPresence API method to set bot users as "away."
https://api.slack.com/bot-users

You can manually set presence using the methods here:
https://slack-rs.github.io/slack-rs/slack/api/users/index.html
But you shouldn't need to (?)

Perhaps manual pings need to be sent. Currently we just respond to server pings.

**Comment by ollivera** [comment]
It is not clear what should be done. Maybe they wait a pong, if they don't receive it after a certain amount the time the bot is marked as inactive. It is just a guess.

**Comment by BenTheElder** [comment]
I'm not sure either. We should be replying with pongs currently, I'm not
aware of anything else a bot is expected to do to stay online. Sending a
ping manually periodically or manually marking active might be a "fix" but
bots are supposed to always be "online" when connected to the rtm client
api.

**Comment by ollivera** [comment]
@BenTheElder My bot is not a real bot user. (https://api.slack.com/bot-users). So, it explains why it doesn't behavior as expected. I am using a regular user to test as I don't have integrations available at moment.

**Comment by BenTheElder** [comment]
> My bot is not a real bot user.

Ah, yes this crate is designed with the bot-user's api in mind. You will probably need to (manually) [mark active](https://slack-rs.github.io/slack-rs/slack/api/users/fn.set_active.html) regularly when the bot is not sending messages.

These are the relevant docs for non-bot users: https://api.slack.com/docs/presence
