### ISSUE TITLE
MissingFieldError title for message type 'file_shared'

### ISSUE THREAD

**Issue by vampolo** [slack-rs/slack-rs#64]
By running the example after a couple of minutes i see

```
on_event(event: Err(JsonDecode(MissingFieldError("title"))), raw_json: "{\"type\":\"file_shared\",\"file_id\":\"F220T0G94\",\"user_id\":\"U0PNT0U2F\",\"file\":{\"id\":\"F220T0G94\"},\"event_ts\":\"1472837203.801148\"}")
thread 'main' panicked at 'Message not supported: Json Decode Error: MissingFieldError("title"), {"type":"file_shared","file_id":"F220T0G94","user_id":"U0PNT0U2F","file":{"id":"F220T0G94"},"event_ts":"1472837203.801148"}', src/main.rs:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm still learning rust and i might be wrong but it is complaining by a missing `title` in the file. Probably a data structure should be updated ?

**Comment by BenTheElder** [comment]
It looks like the title field of the File object will have to be made
Optional. The slack docs don't seem to declare it as required or optional...
https://api.slack.com/types/file

**Comment by vampolo** [comment]
I went ahead, downloaded the `slack-rs` and `slack-api` crates and changed `File` to have all Optional fields except id. Now it works.

I dunno if this is the intended change tho, or it is better to have a `struct FileID` with just a `id: String` and a `struct File` with all the properties.

**Comment by BenTheElder** [comment]
I will look at putting out a fixed release when I get a chance. I plan to
look through the slack docs and check for any further discrepancies with
our types.

**Comment by vampolo** [comment]
On the same topic i just got

```
on_event(event: Err(JsonDecode(MissingFieldError("name"))), raw_json: "{\"type\":\"reaction_added\",\"user\":\"U0M1SV2Q4\",\"item\":{\"type\":\"file\",\"file\":\"F27QTLX8A\"},\"reaction\":\"sunglasses\",\"item_user\":\"USLACKBOT\",\"event_ts\":\"1472968225.211377\"}")
thread 'main' panicked at 'Message not supported: Json Decode Error: MissingFieldError("name"), {"type":"reaction_added","user":"U0M1SV2Q4","item":{"type":"file","file":"F27QTLX8A"},"reaction":"sunglasses","item_user":"USLACKBOT","event_ts":"1472968225.211377"}', src/main.rs:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.```

Seems that another field, on another `struct`, should also be marked optional.

@BenTheElder let me know if i should keep you posted on these here, if you prefer me to open bugs against `slack-api` or if you don't want me to ping you on these issues.

**Comment by BenTheElder** [comment]
The second error should be the same as https://github.com/slack-rs/slack-rs-api/issues/25, we need to replace the structure(s) on reaction event items entirely.

I'm perfectly fine with issues being opened on either and with being pinged but I'm admittedly focused on classes and other projects at the moment.

**Comment by BenTheElder** [comment]
This should be fixed.
