### ISSUE TITLE
sleep/loop in the context of `on_connect` breaks

### ISSUE THREAD

**Issue by blakehawkins** [slack-rs/slack-rs#74]
Hi,

I have all my business logic for a slack-rs handler in the `on_connect` handler.

This includes a loop with thread::sleep to keep doing something periodically.

Sadly, when I do so, `send_message` doesn't work.

I suspect this is because some sort of websocket is closing due to some rules I don't know about.

Any advice appreciated.

**Comment by dten** [comment]
The handler's callbacks are called synchronously. If you never return from one then you've locked up the system.

Don't do that

You should have your long running task on another thread so that both can continue working

**Comment by blakehawkins** [comment]
I'm happy to have it lock the process - once I spawn the client, nothing more needs to be done except block and occasionally send messages. (thread::sleep shouldn't spin?)

I've tried replacing the logic, instead of:

```
Client {
  on_connect { loop { business_logic; sleep } }
}

main { Client::new }
```

I take instead:

```
Client {
  on_connect { business_logic; }
}

main { loop { Client::new; sleep } }
```

But that doesn't work either - it seems the RtmClient never returns?

* possible something else I'm doing with reqwest is blocking I guess - I haven't made an MWE.
* also possible that having a separate thread is a formal requirement? still seems weird the client never returns.

Can you clarify what the client should do, @dten ?

**Comment by dten** [comment]
Hey @blakehawkins the rtm client is a loop that handles incoming websocket events and gives you an eat interface to handle them. It exits when closed or on error.

It sounds like you're not interested in handling events from slack, and just sending messages. Does that sound right? It may be easier to just use slack-rs-api which wraps the web api and is what this crates uses to send messages

**Comment by blakehawkins** [comment]
@dten for now I don't need to see events, but in future I would like to.

I've gone with your original suggestion to spawn a thread, but that doesn't work either. Code looks like this -

```
Client { on_event { // this part works } on_connect { // this part works } }

main {
  Client::new {
    thread::spawn(move || {
      loop { sleep; client.send_message // this doens't work }
    })
  }
}
```

Is it just not possible to do what I'm trying?

**Comment by dten** [comment]
I think you're going to have to post some actual code. When you say "send_message doesn't work" what happens? It never returns or you get an Error? If an error what was it?

**Comment by blakehawkins** [comment]
@dten thanks for the response.

I've managed to get periodic message sending to work using a separate web hooks API.

It looks to me like I'll have to use  both the web hooks client, and this client separately, to do what I want.

* key point is, I don't think slack-rs can maintain a connection for periodically pushing. Is that right?

**Comment by dten** [comment]
very little functionality is exposed by slack-rs for talking _to_ slack, it's mostly for receiving events.
slack-rs can maintain a connection, but personally I don't send anything back through the websocket. don't lock up the `RtmClient` and you will receive events nicely until either slack kicks you off or your internet dies (which _will_ happen so handle it)

**Comment by blakehawkins** [comment]
Okay, I think this can be closed, but probably the README ought to suggest that this isn't for sending periodic message *to* slack on an event loop, to prevent others from experiencing this pain.

**Comment by dten** [comment]
Even Slack suggests not to use the rtm api for sending messages https://api.slack.com/rtm and never returning from a client's event handler is always bad practice, a large number of them will be waiting for you to say you're done

> The RTM API only supports posting simple messages formatted using our default message formatting mode. It does not support attachments or other message formatting modes. To post a more complex message as a user clients can call the chat.postMessage Web API method with as_user set to true.

**Comment by blakehawkins** [comment]
> Even Slack suggests not to use the rtm api for sending messages https://api.slack.com/rtm

It really doesn't say that, but I don't think it's interesting to debate.

Assuming you're right, I don't think it's worth assuming that users of slack-rs are also readers of api.slack.com

> and never returning from a client's event handler is always bad practice, a large number of them will be waiting for you to say you're done

that's a fair lesson learned, but I've found that, even when doing backflips to ensure that I hadn't broken that invariant, I still couldn't get slack-rs to handle both sending periodic message, and reading/responding to events.

**Comment by BenTheElder** [comment]
The methods in `EventHandler` are called from the RTM event loop, as @dten said, the RTM api is built on websockets and requires periodic ping/pong for keep-alive and event handlers are expected to return in a reasonably short period.

If you have long running work to do you will have to use another thread, and the easiest way is probably to just post messages via `slack-rs-api`. Perhaps we should document this in more detail somewhere.

I do fall back heavily on the slack api because they do have pretty good official docs for everything. Nearly all methods in `slack-rs` link to the official docs for some api they wrap, and types for the official type they mimic. It does appear however that the `RTMClient` does not link to the rtm api page currently. That seems like an oversight, though I believe the readme does.

**Comment by blakehawkins** [comment]
> The methods in EventHandler are called from the RTM event loop, as @dten said, the RTM api is built on websockets and requires periodic ping/pong for keep-alive and event handlers are expected to return in a reasonably short period.

Okay, thanks. I think in my case part of the issue was just inexperience with websocket so wasn't aware of the requirements.

> If you have long running work to do you will have to use another thread, and the easiest way is probably to just post messages via slack-rs-api. Perhaps we should document this in more detail somewhere.

As above, I tried a few implementations of threaded approach, but I never got it quite right [or slack-rs didn't quite do what I think it ought to have]. Agree that slack-rs-api is the right tool to use for the sending side.

> I do fall back heavily on the slack api because they do have pretty good official docs for everything. Nearly all methods in slack-rs link to the official docs for some api they wrap, and types for the official type they mimic. It does appear however that the RTMClient does not link to the rtm api page currently. That seems like an oversight, though I believe the readme does.

Absolutely I think it's fair to refer to official docs for extra detail.

--

If there's anything I can do to improve the readme, let me know. For now, closing.
