### ISSUE TITLE
Cannot login with 0.17

### ISSUE THREAD

**Issue by dten** [slack-rs/slack-rs#78]
So I've updated to 0.17 but `RtmClient::login` fails. The reported error is just
`Api("rtm::StartError: JSON error")`

Did some digging to get
`ErrorImpl { code: Message("invalid type: sequence, expected a map"), line: 1, column: 35882 }`

That would be `"fields":[]` contained in a `profile` of a `user` in `users` in the `startresponse`
We have no custom fields because we don't have the paid features so the list being empty seems fair. The expected type though is an object so it says no
https://github.com/slack-rs/slack-api-schemas/blob/master/objects/user_profile.json#L44
50 or so users have `"fields": null,` the other 20 ish have "fields": [],

https://api.slack.com/types/user does not not mention what the types of fields should be

but right now it won't login with 0.17 :( sad times

**Comment by dten** [comment]
Some people have fields! and it looks like this

```
"fields": {
                    "$SOMEGUID": {
                        "value": "$THEVALUE",
                        "alt": ""
                    }
                },
```

**Comment by compressed** [comment]
@dten what if you try setting the `fields` to `null` for the `fields: []` user(s) using the tester API? (see here: https://api.slack.com/methods/users.profile.set). I remember seeing this at one point. I believe it is a slack bug where they have an inconsistent internal data representation (probably `fields` changed from an array to an object at some point and older users have the array representation).

**Comment by dten** [comment]
that test method lets me set it to `null` `[]` and some appropriate object.
However, if a user edits their profile they seem to go from `null` to `[]` so if i could fix everyone's fields they would probably be set back after not too long. Those with nulls and those without cover a wide range of dates from early last year to a few days ago for both.

**Comment by compressed** [comment]
Oh interesting I see, weird. So I guess this has to be fixed then in the underlying `slack-api` crate. We'll need to manually impl deserialize for `UserProfile`: https://github.com/slack-rs/slack-rs-api/blob/master/src/types.rs#L887 to support different object types for field, probably an untagged enum representation to support both `Array` and `Object` serde types.

**Comment by mthjones** [comment]
So the fields can be any of `null`, `[]` or a full object? Oy vey, Slack. And the entire field's existence is undocumented too.

Anyways, it should be relatively simple to fix with the schemas, if you want to PR it. Just change that one field definition to `oneOf` and say it can either be the existing object or an array. The generator picks those up and turns them into enums. Just make sure to give each a title so the variant names can be generated. Here's some examples: https://github.com/slack-rs/slack-api-schemas/search?utf8=%E2%9C%93&q=oneof&type=

**Comment by dten** [comment]
I'll give it a shot :) thanks for pointer

**Comment by dten** [comment]
I've been trying but it seems to me that `oneOf` requires that the variant be tagged with a `"type"` field.

**Comment by dten** [comment]
I'm a little confused about the whole thing but I have something working for

First to the generator so it can generate untagged enum deserialize
https://github.com/slack-rs/slack-rs-api/pull/38

Second to the schema to specif `fields` is an untagged enum of map, or array (of string cause.. there is no actual type?)
https://github.com/slack-rs/slack-api-schemas/pull/2

look about right?

**Comment by mthjones** [comment]
Will take feedback over to the individual PRs. Thanks for doing that!

**Comment by BenTheElder** [comment]
@dten If I'm reading that twitter conversation correctly, this is a bug with slack upstream? Is there any way to track when it will be fixed?

**Comment by dten** [comment]
Not that i know of

**Comment by jordonsc** [comment]
Hi all,

What's the plan of attack with this one, are we waiting for Slack to resolve the issue? This library is non-functional right now, and I don't see any easy way to avoid the issue outside of forking and applying @dten's changes.

Thanks

**Comment by mthjones** [comment]
@dten is working on the fix in a PR in slack-rs-api. Should be in soon.
Will release new version there and here when it is merged.

**Comment by jordonsc** [comment]
Legends, thanks guys!

**Comment by mthjones** [comment]
This should now be fixed with a `cargo update` if you have a lock file, or doing a fresh build. Will release a new version of this library soon to ensure it uses >=0.16.1. @BenTheElder ?

**Comment by BenTheElder** [comment]
Yes. I'll get out a release soonish.

**Comment by BenTheElder** [comment]
`slack-rs 0.17.1` release went out this evening.

@dten when you get a chance could you confirm if this fixed the problem with your users?

**Comment by jordonsc** [comment]
It's now working for me. Thanks!

**Comment by dten** [comment]
Yes it's all good! Had a separate issue but I'm investigating
