### ISSUE TITLE
Message formatting with Sender::send_message not working

### ISSUE THREAD

**Issue by bwasty** [slack-rs/slack-rs#79]
I'm currently upgrading from 0.16 to 0.17. I've converted from `RtmClient::post_message` to `RtmClient::sender::send_message` since the former was removed, but now links formatted with Slack's `<url|replacementText>` syntax don't work anymore - what arrives in the slack channel is the "raw version" (e.g. `<https://s.slack.com/files/slackbot/F123455/|more...>`).

From the `MessageSent` event that is received afterwards it looks like the message is HTML escaped - the angle brackets appear as `&lt;` and `&gt;`.

I've tried to locate where this happens, but at least [here](https://github.com/slack-rs/slack-rs/blob/dc475619ef8a6ddf59a4d0b70c7f6ae7f39ac88a/src/lib.rs#L109) the `msg_json` looks fine (added a print after that line).

Any ideas?

**Comment by BenTheElder** [comment]
https://slack-rs.github.io/slack-rs/slack_api/chat/fn.post_message.html

That should be the closest equivilant now, we removed the web (HTTP, not websocket) api methods from slack-rs in favor the of the API sub crate. `send_message` is via the RTM (websocket) API which does not support that formatting.

> Formatting messages
> The RTM API only supports posting simple messages formatted using our default message formatting mode. It does not support attachments or other message formatting modes. To post a more complex message as a user clients can call the chat.postMessage Web API method with as_user set to true.

(https://api.slack.com/rtm)

**Comment by bwasty** [comment]
@BenTheElder Thanks, that one works (though it was quite difficult to get compiling, see my comment in #81).
Slightly related question before closing: Seems that most operations are more verbose now. For the API calls it makes sense I guess, but things like `get_id` and `get_channel_id` would still be very useful in the library - any reason against adding them back?
