### ISSUE TITLE
Upgrade slack-rs-api version to 0.17

### ISSUE THREAD

**Issue by BenTheElder** [slack-rs/slack-rs#84]
The api crate has had a minor version bump (0.17.0) since the last slack-rs release, we should switch to it.

**Comment by mthjones** [comment]
It's a major bump (pre-1.0), so will warrant a major bump here as well. There's a new `rtm.connect` API that might be worth checking out.

**Comment by BenTheElder** [comment]
Ah, yes. I'm treating it as a major bump but calling it a minor (because
semver). I'll put out a slack-rs 0.18.0 here in a moment with the
dependency update.

I think we should hold off on `rtm.connect` now, as I remember it returns
less information than `rtm.start`; I'd like to open a separate issue
gauging interest in `rtm.connect`.

**Comment by BenTheElder** [comment]
closed in https://github.com/slack-rs/slack-rs/commit/b8f666751833067ccf6ab6b79a4725b8bc1abc93

**Comment by mthjones** [comment]
It's too late now (just read the other issue comments), but I released a minor/patch release with the client export change as well, if you didn't want to do the whole major version bump yet. ;)
