### ISSUE TITLE
Maintainers Needed

### ISSUE THREAD

**Issue by BenTheElder** [slack-rs/slack-rs#90]
I have a full time job now working on Kubernetes related tooling at Google and I don't really expect to have enough time/interest to continue maintaining this myself.  If anyone is interested this project could use other people to step up and maintain it.

/cc @mthjones @dten @squidpickles

**Comment by squidpickles** [comment]
@BenTheElder I'm just getting started at a new company myself, and feeling a bit swamped. I may send a little attention this way in a few months, but my Slack bot remains a tiny hobby project, and doesn't cover enough of the "bot space" to get me poking around too often.
Happy to ping folks when I come back to the land of the living, but for now, I can't take it on.

**Comment by BenTheElder** [comment]
Thanks for checking in! Hopefully someone else will come along and take it
up, I'd hate to just leave it abandoned.

**Comment by dten** [comment]
I don't mind helping out. I can't commit tons of time but I do use the thing every day and have desires to keep it running :)

**Comment by BenTheElder** [comment]
Thanks! Let me get you added to the org.

**Comment by dten** [comment]
Great I'm in, now to leave misleading comments with authority! :)

**Comment by compressed** [comment]
@BenTheElder congrats, Kubernetes needs the help :smile: 

I don't mind helping out either. I still have my futures branch sticking around somewhere which as I am seeing now could help fix some of the open issues.

**Comment by compressed** [comment]
Oh I was also thinking - is there a way to allow multiple people to publish the new versions of the crates? Ideally we'd need to be able to do that too.

**Comment by compressed** [comment]
Found that answer - It seems possible to add the GitHub org to crates.io owners (or maybe it is already): http://doc.crates.io/crates-io.html#cargo-owner

**Comment by BenTheElder** [comment]
Thanks @compressed, I'll add you and set up team ownership momentarily. :-)

**Comment by BenTheElder** [comment]
I've confirmed `github:slack-rs:maintainers` is already an owner of `slack-rs` on cargo.

**Comment by compressed** [comment]
Great thanks! :+1:

**Comment by mthjones** [comment]
Thanks all! I'm in about the same boat, without the time/interest to work on this project due to work and contributing to other projects I'm actively using. I appreciate you guys helping out! 😄

**Comment by BenTheElder** [comment]
xref: https://github.com/slack-rs/slack-rs/pull/112
