### ISSUE TITLE
Getting User Handle

### ISSUE THREAD

**Issue by joncatanio** [slack-rs/slack-rs#94]
Is there currently any way to get the user handle? (e.g. @noj is my handle) I can't seem to get it from the StartResponse struct or UserProfile struct within that.

**Comment by dten** [comment]
The User details are on slf

https://docs.rs/slack_api/0.18.0/slack_api/rtm/struct.StartResponse.html#structfield.slf

**Comment by joncatanio** [comment]
Yeah I noticed the User struct is there under `slf`and `users` fields. I am using that but the `name` field in the User struct seems to just give me the user's email name not their Slack handle. For instance, if a user with the Slack handle @TestUser has the email `testman123@gmail.com` the User struct will give me `testman123` as the `name` where I want `TestUser` (the slack handle).

**Comment by dten** [comment]
Hmmm... I'm currently using `name` to get exactly what you're after.
I thought slack had changed their policies to make it harder to get emails also.
Will have a look but could you paste something here maybe that isn't working

**Comment by joncatanio** [comment]
Interesting, I'm in class right now but I'll send more info in a bit. Maybe it's some settings in my Slack workplace? I'm getting a bunch of email data so that's interesting.

**Comment by dten** [comment]
i changed my on_connect to 

```
    fn on_connect(&mut self, cli: &slack::RtmClient){
        panic!("{:?}", cli.start_response().slf);
    }
```

and I get this (i started out the id, it was some random chars but maybe should be secret

```
thread 'main' panicked at 'Some(User { color: None, deleted: None, has_2fa: None, id: Some("U********"), is_admin: None, is_owner: None, is_primary_owner: None, is_restricted: None, is_ultra_restricted: None, name: Some("sir_botalot"), profile: None, two_factor_type: None })', src\main.rs:447:8
```

as you can see my bot's name, `sir_botalot` is under name

**Comment by dten** [comment]
i tried changing my display name in my profile. `name` didn't change" but the field `displayname` which is not listed on the api docs on slack.com did change. That results in my use case picking the wrong name 👎 as it used name

**Comment by dten** [comment]
https://api.slack.com/changelog/2017-09-the-one-about-usernames this seems relevant

**Comment by dten** [comment]
tried changing my change to `<@name>` and it works now :)

**Comment by joncatanio** [comment]
Hmm... this is so strange. So when I do that API test that you mention above I can see everything is there but for instance here is some output by printing the entire `StartResponse` struct.

`User { color: Some("3c989f"), deleted: Some(false), has_2fa: None, id: Some("U********"), is_admin: Some(false), is_owner: Some(false), is_primary_owner: Some(false), is_restricted: Some(false), is_ultra_restricted: Some(false), name: Some("y4zt*********"), profile: Some(UserProfile { email: Some("y4zt*********@gmail.com"), fields: None, first_name: None, image_1024: Some("https://avatars.slack-edge.com/2017-09-17/241882714192_e423eb0a78002bacf086_1024.jpg"), image_192: Some("https://avatars.slack-edge.com/2017-09-17/241882714192_e423eb0a78002bacf086_192.jpg"), image_24: Some("https://avatars.slack-edge.com/2017-09-17/241882714192_e423eb0a78002bacf086_24.jpg"), image_32: Some("https://avatars.slack-edge.com/2017-09-17/241882714192_e423eb0a78002bacf086_32.jpg"), image_48: Some("https://avatars.slack-edge.com/2017-09-17/241882714192_e423eb0a78002bacf086_48.jpg"), image_512: Some("https://avatars.slack-edge.com/2017-09-17/241882714192_e423eb0a78002bacf086_512.jpg"), image_72: Some("https://avatars.slack-edge.com/2017-09-17/241882714192_e423eb0a78002bacf086_72.jpg"), image_original: Some("https://avatars.slack-edge.com/2017-09-17/241882714192_e423eb0a78002bacf086_original.jpg"), last_name: None, phone: None, skype: None }), two_factor_type: None }`

Notice that the `first_name` and `last_name` fields are `None`, but I can clearly see his name in slack. He doesn't have a `display_name` set but I see that there is a `display_name` field in the API test (the one you linked) though it's not populated and that's correct. But the `first_name` and `last_name` fields ought to be.

When you say
> change to <@name> and it works now :)

What does that actually mean? Like in the Slack client you changed your name? Because I have noticed that when I create an account the API returns a lot of `None` values until I actually edit my profile and click "Save", do you know why that is?

**Comment by joncatanio** [comment]
I would like to get a hold of the display name and full name if possible.

**Comment by joncatanio** [comment]
Does your response contain the `display_name` and `display_name_normalized` fields under the `profile` field as noted in the article?

**Comment by dten** [comment]
looks to me that isn't included in `self`'s version of the data. You can lookup more data from the full list of `users`, this version hasn't got a field for display_name yet though.

Again if you read the article what's the use case for needing `display_name`s?

If you wish to mention someone in a slack message use `<@id>` where is is `U*******` as above, if you want to know who was mentioned in messages the blog says you can do that too

**Comment by dten** [comment]
I tried changing my displayname back, the message where i used `<@id>` to ref myself auto updated it's displayname, the one where i used the raw text did not. Guess that's why they want to separate the two

**Comment by joncatanio** [comment]
Ahh I see. I can work with that. I was basically just building a quick project to get familiar with Rust. It is a slackbot that handles karma. Like a bunch of other projects `username++` gives you 1 point of whatever. So I wanted to make it robust and try to infer which user should get karma based on the `first_name`, `last_name`, `display_name` fields. But it sounds like I'll just need to focus on mentions only.

**Comment by joncatanio** [comment]
We can probably close this issue then. I'll work around the `display_name` thing. Thanks so much for your help!

**Comment by dten** [comment]
no problem! closing for now then 👍
