### ISSUE TITLE
Subscribe to presence events

### ISSUE THREAD

**Issue by Mandragorian** [slack-rs/slack-rs#98]
It seems that since January 2018 [presence events are not reported unless subscribed to](https://api.slack.com/events/presence_change). I think that this is not supported by slack-rs, so user presence can not be tracked.

**Comment by dten** [comment]
Maybe I'm missing something but the docs seem to just loop. What's required to subscribe?

**Comment by Mandragorian** [comment]
I see the following in the documentation:

> As of January 2018, presence_change events are not dispatched without presence subscriptions
> established with presence_sub. Relatedly, current user presence status is no longer communicated  > rtm.start. Learn more. 

As far as i can tell this means that unless a user explicitly requests for presence change events to be sent, they wont receive such events through the RTM API.

**Comment by dten** [comment]
Ah I see https://api.slack.com/docs/presence-and-status#subscriptions

Lo🤨

**Comment by markniebur** [comment]
Should this issue be closed since that change was merged?

**Comment by dten** [comment]
Yes! Also I should release a version.

**Comment by dten** [comment]
Released a version now so closing
